spring:
  data:
    mongodb:
      host: ${MONGODB_HOSTNAME:localhost}
      port: 27017
      database: project_final
      auto-index-creation: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://${DPSQL_HOSTNAME:localhost}:5432/postgres
    username: postgres
    password: password
  jpa:
      hibernate:
        ddl-auto: update


server:
  port: 8081

