spring:
  data:
    mongodb:
      host: ${MONGODB_HOSTNAME:localhost}
      port: 27017
      database: project_final
      auto-index-creation: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://${DPSQL_HOSTNAME:localhost}:5432/postgres
    username: postgres
    password: password
  jpa:
      hibernate:
        ddl-auto: update


Remote:
  url_update: http://${MENU_CONTAINER:localhost}:8082/menus/put/update_location_menus
  url_delete: http://${MENU_CONTAINER:localhost}:8082/menus/delete/delete_location_menus/



server:
  port: 8081

